language: android

android:
  components:
    - tools
    - platform-tools
    - tools
    - build-tools-27.0.3
    - android-27
    - android-25 //Android platform used by alternative emulator
    - sys-img-armeabi-v7a-android-25

notifications:
  - email: false

before_install:
  - yes | sdkmanager "platforms;android-28"

before_script:
  - echo no | android create avd --force -n test -t android-25 --abi armeabi-v7a
  - emulator -avd test -no-audio -no-window &
  - android-wait-for-emulator
  - adb shell input keyevent 82 &
  

script:
  - ./gradlew build test
  - ./gradlew connectedCheck
